samples: samples.csv
units: units.csv
ref_dir: /home/groups/carilee/refs/hg38/
ref_fasta: Homo_sapiens_assembly38.fasta
known_sites: dbsnp_146.hg38.vcf.gz
exome_targets: /home/groups/carilee/refs/Twist_Exome_Target_hg38.bed
germline_resource: /home/groups/carilee/refs/gnomAD/af-only-gnomad.hg38.vcf.gz
contamination_resource: /home/groups/carilee/refs/gnomAD/small_exac_common_3.hg38.vcf.gz
