samples: samples.csv
units: units.csv
ref_dir: data/hg38
ref_fasta: genome.chr21.fa
known_sites: dbsnp.vcf.gz
exome_targets: data/hg38/hg38.chr21.exons.bed
germline_resource: data/hg38/gnomad_short.vcf.gz
contamination_resource: data/hg38/contam_short.vcf.gz
