# CSV file with single column, patient, with every patient ID
patients: patients_test.csv
# CSV file with info on each sample
units: units_test.csv

# Reference genome sources
# Directory where reference fasta and supporting files are stored
ref_dir: /home/groups/carilee/refs/hg38/
# Name of reference FASTA (should be unzipped)
ref_fasta: Homo_sapiens_assembly38.fasta
# Comma separated names of VCF files with known mutations. 
# Should all be in the reference directory
known_sites: dbsnp_146.hg38.vcf.gz, resources-broad-hg38-v0-Homo_sapiens_assembly38.known_indels.vcf.gz, 1000G_phase1.snps.high_confidence.hg38.vcf.gz
# BED file with exome regions that were targeted for capture. Doesn't have to be in ref_dir
capture_targets: /home/groups/carilee/refs/coverage/agilent-exonsV5/S04380110_Covered.bed
# AF only VCF with common allele frequencies - use gnomAD file
germline_resource: /home/groups/carilee/refs/gnomAD/af-only-gnomad.hg38.vcf.gz
# Biallelic variants only VCF with AF data - use EXAC file
contamination_resource: /home/groups/carilee/refs/gnomAD/small_exac_common_3.hg38.vcf.gz

# GATK TMP directory
# Large files may overwhelm the default tmp directory (/tmp)
# Set this variable to an alternative filepath that has larger storage (ie $SCRATCH) if
# GATK is running out of storage during a run
tmp_dir: /scratch/users/tbencomo/tmp/

## Parallelism
# Number of Mutect2 workers per sample
num_workers: 2

# Apply additional thresholds to filter variants
# When set to true, requires each SNV has a minimum of
# 15 reads covering the position and at least 5 reads
# with the mutant allele.
# When false, only use FilterMutectCalls criteria
stringent_filtering: false


# Annotation data sources
# Directory with VEP annotation data
vep_dir: /home/groups/carilee/refs/vep_data
# Assembly version name
assembly_version: GRCh38
# Value for Center field in the combined MAF
center_name: lee-lab
# Alternate Isoforms For vcf2maf Selection. Set as None to use Ensembl defaults
alternate_isoforms: None


# Mutect2 Mode
# Allows somatic variant calling without matched normal
# Only advised as a last resort - try to get matched normal samples
tumor_only: false

# Panel of Normal (PON)
# Use PON with Mutect2 for variant calling
use_pon: true
# Filepath for PON. To create a new PON from all the normal samples, specify as None
pon_vcf: /home/groups/carilee/refs/broad-pons/1000g_pon.hg38.vcf.gz
# GATK, Picard, or BED style interval file with intervals to use for Panel of Normal Creation
interval_file: /home/groups/carilee/refs/hg38/wgs_calling_regions.hg38.interval_list

## Singularity Containers
## This specifies the container to use for various steps in the pipeline
## The value can be any string (either local path or url) that can be queried using singularity pull
gatk_container: docker://broadinstitute/gatk:4.2.0.0
multiqc_container: docker://ewels/multiqc:v1.6
mosdepth_container: docker://brentp/mosdepth:v0.3.1
fastqc_container: docker://biocontainers/fastqc:v0.11.9_cv8
bwa_container: docker://tbencomo/bwa-samtools
vep_container: docker://tbencomo/vep-vcf2maf
eda_container: docker://tbencomo/eda
